"""YAML manifest parsing for audiobook configuration."""

from __future__ import annotations

import os

import yaml

from audiobook.models import BookMetadata


def find_manifest(input_path: str) -> str | None:
    """Look for manifest.yml in the input directory."""
    candidate = os.path.join(input_path, "manifest.yml")
    if os.path.isfile(candidate):
        return candidate
    return None


def load_manifest(manifest_path: str) -> dict:
    """Load and return the raw manifest dict from a YAML file."""
    with open(manifest_path, "r") as f:
        return yaml.safe_load(f) or {}


def get_file_order(manifest: dict, input_dir: str) -> list[str] | None:
    """Return ordered list of absolute file paths from manifest chapters.

    Returns None if the manifest has no chapters section.
    """
    chapters = manifest.get("chapters")
    if not chapters:
        return None

    paths = []
    for ch in chapters:
        filename = ch.get("file", "")
        path = os.path.join(input_dir, filename)
        if os.path.isfile(path):
            paths.append(os.path.abspath(path))
    return paths


def get_chapter_titles(manifest: dict) -> dict[str, str]:
    """Return a mapping of filename -> chapter title from manifest."""
    titles = {}
    chapters = manifest.get("chapters")
    if not chapters:
        return titles

    for ch in chapters:
        filename = ch.get("file", "")
        title = ch.get("title", "")
        if filename and title:
            titles[filename] = title
    return titles


def get_metadata(manifest: dict) -> BookMetadata:
    """Extract BookMetadata from manifest, leaving missing fields as defaults."""
    return BookMetadata(
        title=manifest.get("title", ""),
        author=manifest.get("author", ""),
        narrator=manifest.get("narrator", ""),
        series=manifest.get("series", ""),
        year=str(manifest.get("year", "")),
        genre=manifest.get("genre", "Audiobook"),
        description=manifest.get("description", ""),
        cover=manifest.get("cover", ""),
    )


def generate_manifest_yaml(
    metadata: BookMetadata,
    chapters: list[dict],
    input_path: str,
) -> str:
    """Generate manifest YAML content as a string."""
    lines = [
        "# Generated by: audiobook init {}".format(input_path),
        "# Edit this file to customize your audiobook, then run:",
        "#   audiobook convert {}".format(input_path),
        "",
        'title: "{}"'.format(metadata.title),
        'author: "{}"'.format(metadata.author),
        'narrator: "{}"'.format(metadata.narrator),
        'series: "{}"'.format(metadata.series),
        'year: "{}"'.format(metadata.year),
        'genre: "{}"'.format(metadata.genre),
        'description: "{}"'.format(metadata.description),
        'cover: "{}"'.format(metadata.cover),
        "",
        "chapters:",
    ]

    for ch in chapters:
        lines.append('  - file: "{}"'.format(ch["file"]))
        lines.append('    title: "{}"'.format(ch["title"]))
        lines.append('    duration: "{}"'.format(ch["duration"]))
        lines.append("")

    return "\n".join(lines)
